ルーティング処理の修正
MMachida1461/memo_practice pull request #2
Opened 2024-09-22 04:19 UTC by MMachida1461

昨日、レビューしていただいたことを頭に入れながら
主に、ルーティングの処理を修正しました。
レビューよろしくお願いします。

2024-09-22 14:28 UTC, MizukiMatsutani requested changes
コメントしました！

内容確認して、「次回PRでいいが・・・」と書いていないものは修正してみてください！

2024-09-22 14:28 UTC, MizukiMatsutani commented on routes/web.php
> +        Route::get('/delete', [MemoController::class, 'delete'])->name('delete');
削除の実行処理はpostが好ましいです！
一番いいのはpostでもなくdelete HTTPメソッドがよいですが、ブラウザが対応していないこともあるため、postが良いかと思います

2024-09-22 14:28 UTC, MizukiMatsutani commented on routes/web.php
> +    Route::post('create', [MemoController::class, 'create'])->name('create');
実はこのあたり作成画面表示はcreateで作成処理はstoreという名前をつけるのがLaravelのデフォルトの命名規則です！

https://readouble.com/laravel/11.x/ja/controllers.html#actions-handled-by-resource-controller

別にこれに習わなくては行けないこともないですが、Laravel的な普通を知っておくと他のプロジェクトに入るときにスッと理解が高まります！

2024-09-22 14:28 UTC, MizukiMatsutani commented on routes/web.php
> +Route::prefix('/memos')->name('memos.')->group(function() {
このPRでは不要ですが、次は「ログインしていなければアクセスできないようにする」という処理を作ってみてください！

2024-09-22 14:28 UTC, MizukiMatsutani commented on app/Http/Controllers/MemoController.php
> +        $memos = Memo::all();
ページネーションはやめたのですか？？
やめても構いませんが、コメントアウトの説明は嘘を書いたままですので、コメントアウトは削除しましょう！

あと、コメントアウトは修正漏れが発生しやすいため、自明な処理はコメントを書かないほうがいいですよ！（ただ、勉強のためでしょうから、説明や理解を自分のために記載するのはいいことです）

本当のプロダクトコードでは「コードをコメントアウトで説明しないといけないような複雑な書き方はしない」ということを心がけましょう！

2024-09-22 14:28 UTC, MizukiMatsutani commented on app/Http/Controllers/MemoController.php
>          if(!$memo_edit){
ここは前回MTG中に指摘した内容と同じで、findOrFailをしている時点でこのifは不要となります！

2024-09-22 14:28 UTC, MizukiMatsutani commented on app/Http/Controllers/MemoController.php
>          $request->validate([
次のPRで修正でよいですが、バリデーションの処理をコントローラに書くと「ファットコントローラー」といってアンチパターンに陥りがちです！
LaravelではFormRequestというバリデーションをカプセル化する仕組みがあるためそちらに切り替えてみましょう！
https://readouble.com/laravel/11.x/ja/validation.html#form-request-validation

2024-09-22 14:28 UTC, MizukiMatsutani commented on app/Http/Controllers/MemoController.php
> +        $memo_delete = Memo::findOrFail($id);
削除に関しては、findOrFailで存在しないときにエラーにしてしまってもよいですが、

Memo::destroy($id); だけでも消せます！
存在しないIDを消そうとしてもSQL的にはエラーにならずに空振りするため、destroyを使うのも手です！
https://readouble.com/laravel/11.x/ja/eloquent.html#deleting-an-existing-model-by-its-primary-key

2024-09-22 14:28 UTC, MizukiMatsutani commented on app/Http/Controllers/MemoController.php
>          $updateMemo->update([
この書き方だとfillableが発動しないため少し危険です！（特にLaravelをよく知らない人とプロジェクトを一緒にする場合）

https://qiita.com/henriquebremenkanp/items/cd13944b0281297217a9#%E3%83%87%E3%83%BC%E3%82%BF%E3%82%92%E5%85%A5%E3%82%8C%E3%82%8B%E3%81%A8%E3%81%8D%E3%82%A4%E3%83%B3%E3%82%B5%E3%83%BC%E3%83%88%E3%81%A7%E3%82%82%E3%82%A2%E3%83%83%E3%83%97%E3%83%87%E3%83%BC%E3%83%88%E3%81%A7%E3%82%82

このあたり見てみるとよいかも！
基本、fill()を使って処理をします！

2024-09-22 14:28 UTC, MizukiMatsutani commented on resources/views/edit.blade.php
>      <meta charset="UTF-8">
コメントする場所がなかったのでこちらに書きますが、
本ファイル（特にmemo関係の詳細や、作成画面、一覧画面も）のbladeファイルの配置場所が気になります！

viewsフォルダにmemosというフォルダを切って、その中にまとめるのが適切かなと思います！

2024-09-22 14:28 UTC, MizukiMatsutani commented on resources/views/edit.blade.php
> +            <input type="hidden" name="memo_id" value="{{ $memos_edit->id }}">
この書き方だと、バリデーションエラー発生時に入力した文字が消えませんか？？
old()を使ってユーザーが入力した値（エラーになった入力値）を画面に表示する処理を入れる必要があります！

2024-09-23 01:19 UTC, MMachida1461 commented on routes/web.php
> +        Route::get('/delete', [MemoController::class, 'delete'])->name('delete');
削除処理、修正しました。
edit.blade.phpのaタグで削除にしていた部分を、formでpostにして削除するように修正しました。

2024-09-23 01:24 UTC, MMachida1461 commented on routes/web.php
> +    Route::post('create', [MemoController::class, 'create'])->name('create');
メソッド名をcreateからstoreに修正しました。
共有いただいた、ページを確認し、思ったのですが
editとupdateの使い分けは

edit　編集画面への遷移
update　編集画面でアップデートした時の処理

というイメージでしょうか？

2024-09-23 01:32 UTC, MMachida1461 commented on app/Http/Controllers/MemoController.php
> +        $memos = Memo::all();
>>ページネーションはやめたのですか？？
現時点で、他のアプリ作成などに進みたく、一旦飛ばしています。
なので、ご指摘通り、コメントを削除しました。

>>コメントアウトは修正漏れが発生しやすいため、自明な処理はコメントを書かないほうがいいですよ！
なるほど、先ほどのレビューでもあったように命名規則もあるし
ルールに沿って、書くこともそこにつながってきますね。気をつけます。
現段階では、メソッドの前だけに『このメソッドは何をしているのか』だけ残すようにしました。

2024-09-23 01:36 UTC, MMachida1461 commented on app/Http/Controllers/MemoController.php
>          if(!$memo_edit){
ご指摘ありがとうございます。
修正しました。

2024-09-23 01:45 UTC, MMachida1461 commented on app/Http/Controllers/MemoController.php
> +        $memo_delete = Memo::findOrFail($id);
ご指摘ありがとうございます。
destroyに修正しました。

修正後、存在しないidを挿入して動作確認しましたが、確かに該当のデータがないため
そのままリダイレクトして、メモ一覧に戻りました。
わかりやすいコードという点でも、修正後の方がわかりやすいです。ありがとうございます。

2024-09-23 02:06 UTC, MMachida1461 commented on app/Http/Controllers/MemoController.php
>          $updateMemo->update([
MemoController、UserControllerの登録、更新処理を
fillメソッドを使用するように修正しました。

2024-09-23 02:11 UTC, MMachida1461 commented on resources/views/edit.blade.php
>      <meta charset="UTF-8">
memosフォルダを作成し、それにあれに合うように修正しました。

2024-09-23 02:37 UTC, MMachida1461 commented on resources/views/edit.blade.php
> +            <input type="hidden" name="memo_id" value="{{ $memos_edit->id }}">
ご指摘ありがとうございます。
修正しました。

2024-09-23 15:07 UTC, MizukiMatsutani commented on app/Http/Controllers/MemoController.php
> +        $createMemo->fill($request->all())->save();
登録系はcreateのままでもよかったです！

2024-09-23 15:07 UTC, MizukiMatsutani commented on app/Http/Controllers/UserController.php
> +        $createUser->fill($request->all())->save();
こちらも登録系なのでcreateでも良かったですよ！

2024-09-26 22:35 UTC, merged